# Generated by Django 3.0.6 on 2020-05-23 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reparto', models.CharField(max_length=50, unique=True)),
                ('codigo_postal', models.CharField(max_length=10, unique=True)),
                ('ciudad', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('es_reparto', models.BooleanField(default=True)),
                ('fecha_creacion_reparto', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Reparto',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('carnet_identidad', models.CharField(max_length=11, unique=True)),
                ('numero_fijo', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_vecino', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_celular', models.CharField(blank=True, max_length=12, null=True)),
                ('numero_trabajo', models.CharField(blank=True, max_length=12, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, unique=True)),
                ('numero_casa', models.PositiveIntegerField(null=True)),
                ('edificio', models.CharField(blank=True, max_length=20)),
                ('calle', models.CharField(max_length=20)),
                ('entre_calle_primera', models.CharField(max_length=20)),
                ('entre_calle_segunda', models.CharField(max_length=20)),
                ('fecha_bautiso', models.DateField(null=True)),
                ('local_bautiso', models.CharField(max_length=20)),
                ('nombre_pastor_bautiso', models.CharField(max_length=80)),
                ('ingresa_por', models.CharField(choices=[('Examen', 'Examen'), ('Testimonio', 'Testimonio'), ('Carta', 'Carta'), ('Bautismo', 'Bautismo')], default='Bautismo', max_length=10)),
                ('fecha_ingreso', models.DateField(null=True)),
                ('profesion', models.CharField(blank=True, max_length=50)),
                ('ocupacion', models.CharField(blank=True, max_length=50)),
                ('foto', models.ImageField(blank=True, upload_to='')),
                ('comentario_extra', models.TextField(blank=True, max_length=200)),
                ('fecha_creacion_contacto', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_reingreso', models.DateField(blank=True, null=True)),
                ('comentario_reingreso', models.TextField(blank=True, max_length=200)),
                ('baja_por', models.CharField(choices=[('Fallecimiento', 'Fallecimiento'), ('Traslado', 'Traslado'), ('Salida', 'Salida'), ('Disciplina', 'Disciplina')], default='Salida', max_length=13)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contact_Web.Reparto')),
            ],
            options={
                'verbose_name_plural': 'Contactos',
            },
        ),
    ]
