# Generated by Django 3.0.6 on 2020-05-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0002_auto_20200523_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='baja_por',
            field=models.CharField(blank=True, choices=[('Fallecimiento', 'Fallecimiento'), ('Traslado', 'Traslado'), ('Salida', 'Salida'), ('Disciplina', 'Disciplina')], max_length=13),
        ),
    ]
