# Generated by Django 3.0.6 on 2020-05-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0004_auto_20200523_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fecha_reingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
