# Generated by Django 3.0.6 on 2020-05-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0007_auto_20200528_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='calle',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='entre_calle_primera',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='entre_calle_segunda',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='numero_casa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
