# Generated by Django 3.0.6 on 2020-05-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0008_auto_20200529_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparto',
            name='codigo_postal',
            field=models.CharField(max_length=10),
        ),
    ]
