# Generated by Django 3.0.6 on 2020-05-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0009_auto_20200529_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reparto',
            name='nombre_reparto',
            field=models.CharField(max_length=50),
        ),
    ]
