# Generated by Django 3.0.6 on 2020-05-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0012_auto_20200529_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='edificio',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
