# Generated by Django 3.0.6 on 2020-05-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0014_auto_20200529_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='baja_por',
            field=models.CharField(choices=[('Fallecimiento', 'Fallecimiento'), ('Traslado', 'Traslado'), ('Salida', 'Salida'), ('Disciplina', 'Disciplina')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='comentario_extra',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='comentario_reingreso',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='ocupacion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
