# Generated by Django 3.0.6 on 2020-05-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0015_auto_20200529_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
