# Generated by Django 3.0.6 on 2020-05-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0016_auto_20200529_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='numero_casa',
            field=models.CharField(blank=True, default=123, max_length=10),
            preserve_default=False,
        ),
    ]
