# Generated by Django 3.0.6 on 2020-05-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0017_auto_20200529_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='edificio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
