# Generated by Django 3.0.6 on 2020-05-29 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0018_auto_20200529_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='calle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='entre_calle_primera',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='entre_calle_segunda',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='ingresa_por',
            field=models.CharField(choices=[('Examen', 'Examen'), ('Testimonio', 'Testimonio'), ('Carta', 'Carta'), ('Bautismo', 'Bautismo')], default='Bautismo', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='local_bautiso',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre_pastor_bautiso',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='reparto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Contact_Web.Reparto'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='segundo_apellido',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
