# Generated by Django 3.0.6 on 2020-05-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0019_auto_20200529_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='local_bautiso',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
