# Generated by Django 3.0.6 on 2020-05-29 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0020_auto_20200529_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='calle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='entre_calle_primera',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='entre_calle_segunda',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
