# Generated by Django 3.0.6 on 2020-06-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0025_auto_20200608_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='comentario_extra',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
