# Generated by Django 3.0.6 on 2020-06-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0026_auto_20200608_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='fecha_bautiso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='Photos/'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='ingresa_por',
            field=models.CharField(blank=True, choices=[('Examen', 'Examen'), ('Testimonio', 'Testimonio'), ('Carta', 'Carta'), ('Bautismo', 'Bautismo')], default='Bautismo', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='local_bautiso',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre_pastor_bautiso',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
