# Generated by Django 3.0.6 on 2020-06-22 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0027_auto_20200622_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='reparto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Contact_Web.Reparto'),
        ),
    ]
