# Generated by Django 3.0.6 on 2020-06-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0029_auto_20200626_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='ingresa_por',
            field=models.CharField(blank=True, choices=[('Examen', 'Examen'), ('Testimonio', 'Testimonio'), ('Carta', 'Carta'), ('Bautismo', 'Bautismo')], max_length=10, null=True),
        ),
    ]
