# Generated by Django 3.0.6 on 2020-06-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0030_auto_20200626_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='sexo',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='ingresa_por',
            field=models.CharField(blank=True, choices=[('Examen', 'Examen'), ('Testimonio', 'Testimonio'), ('Carta', 'Carta'), ('Bautismo', 'Bautismo')], default='Bautismo', max_length=10, null=True),
        ),
    ]
