# Generated by Django 3.0.6 on 2020-06-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0031_auto_20200627_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contacto',
            name='sexo',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='ingresa_por',
            field=models.CharField(blank=True, choices=[('Examen', 'Examen'), ('Testimonio', 'Testimonio'), ('Carta', 'Carta'), ('Bautismo', 'Bautismo')], max_length=10, null=True),
        ),
    ]
