# Generated by Django 3.0.6 on 2020-06-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0032_auto_20200627_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='sexo',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
    ]
