# Generated by Django 3.0.6 on 2020-06-27 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0033_auto_20200627_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='sexo',
        ),
    ]
