# Generated by Django 3.0.6 on 2020-07-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0035_auto_20200627_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='carnet_identidad',
            field=models.PositiveIntegerField(max_length=11, unique=True),
        ),
    ]
