# Generated by Django 3.0.6 on 2020-07-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0039_auto_20200702_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='numero_celular',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='numero_fijo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='numero_trabajo',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='numero_vecino',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
