# Generated by Django 3.0.6 on 2020-07-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact_Web', '0040_auto_20200702_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reparto',
            options={'ordering': ['nombre_reparto'], 'verbose_name_plural': 'Reparto'},
        ),
        migrations.AlterField(
            model_name='contacto',
            name='baja_por',
            field=models.CharField(blank=True, choices=[('Fallecimiento', 'Fallecimiento'), ('Traslado', 'Traslado'), ('Salida', 'Salida'), ('Disciplina', 'Disciplina')], max_length=13, null=True),
        ),
    ]
